trigger: 
- main

pool: 
  vmImage: 'ubuntu-latest'

variables:
  publisherId: 'jorge-codes'        
  extensionId: 'azure-backend-terraform-state-lock-waiter'        
  extensionName: 'Azure Backend Terraform State Lock Waiter'
  artifactName: 'extension'
  visibility: 'private'
  marketplaceServiceConnection: 'd7744d61-b6a6-40d9-b5f7-ed766d9a9584'
  
stages:
  - stage: TestAndValidate
    displayName: 'Run Tests and Validate Code'
    jobs:
      - job: RunTests
        displayName: 'Execute tests'
        steps:
          - task: PowerShell@2
            displayName: 'Clear SourceCode directory'
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                $pathToDelete = '$(Pipeline.Workspace)/SourceCode';
                if (Test-Path -LiteralPath $pathToDelete -PathType Container) {
                  Remove-Item -LiteralPath $pathToDelete -Recurse -Force -ErrorAction SilentlyContinue;
                  Write-Output "Directory '$pathToDelete' removed successfully.";
                } else {
                  Write-Output "Directory '$pathToDelete' does not exist.";
                }

          - checkout: self
            displayName: 'Checkout source code'
            path: 'SourceCode'
            workspaceRepo: false
            
          - task: NodeTool@0
            displayName: Use Node (specified in .nvmrc file)
            inputs:
              versionSource: 'fromFile'
              versionFilePath: '$(Pipeline.Workspace)/SourceCode/task/.nvmrc'

          - task: AzureCLI@2
            displayName: 'Add test .env file'
            inputs:
              azureSubscription: DevOpsUserAccessAutomation (Dev/Test)
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd '$(Pipeline.Workspace)/SourceCode/tests';
                (az appconfig kv show  --name aztappconfig --key JORGE_AZDO_CUSTOM_TASK_EXTENSION_0_TEST_DOTENV | ConvertFrom-Json).value > .env;
                ls -la .| grep '.env';
          
          - task: PowerShell@2
            displayName: 'Install dependencies and run tests (unit and integration)'
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                cd '$(Pipeline.Workspace)/SourceCode/task';
                npm ci;
                npm test;
          
          - task: PublishTestResults@2
            displayName: 'Publish test results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '$(Pipeline.Workspace)/SourceCode/test-results.xml'

  - stage: PackageExtension
    displayName: 'Build and Package Extension'
    # dependsOn: TestAndValidate
    # condition: succeeded()
    jobs:
      - job: PackageExtension
        displayName: 'Create VSIX package'
        steps:
          - task: PowerShell@2
            displayName: 'Clear SourceCode directory'
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                $pathToDelete = '$(Pipeline.Workspace)/SourceCode';
                if (Test-Path -LiteralPath $pathToDelete -PathType Container) {
                  Remove-Item -LiteralPath $pathToDelete -Recurse -Force -ErrorAction SilentlyContinue;
                  Write-Output "Directory '$pathToDelete' removed successfully.";
                } else {
                  Write-Output "Directory '$pathToDelete' does not exist.";
                }

          - checkout: self
            displayName: 'Checkout source code'
            path: 'SourceCode'
            workspaceRepo: false

          - task: TfxInstaller@4
            displayName: 'Install TFX CLI'
            inputs:
              version: "v0.x"

          - task: NodeTool@0
            displayName: Use Node (specified in .nvmrc file)
            inputs:
              versionSource: 'fromFile'
              versionFilePath: '$(Pipeline.Workspace)/SourceCode/task/.nvmrc'

          - task: PowerShell@2
            displayName: 'Build extension'
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                cd '$(Pipeline.Workspace)/SourceCode/task';
                npm ci;
                npm run build;

          - task: AzureCLI@2
            displayName: 'Set marketplace service connection auth token'
            inputs:
              azureSubscription: 'DevOpsUserAccessAutomation'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              useGlobalConfig: true
              inlineScript: |
                $accessToken = az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv
                Write-Host "##vso[task.setsecret]$accessToken"
                Write-Host "##vso[task.setendpoint id=$env:MARKETPLACESERVICECONNECTION;field=authParameter;key=password]$accessToken"


          - task: QueryAzureDevOpsExtensionVersion@4
            name: QueryVersion
            displayName: 'Query current extension version'
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: '$(marketplaceServiceConnection)'
              publisherId: '$(publisherId)'
              extensionId: '$(extensionId)'
              versionAction: 'Patch'
          
          - task: PackageAzureDevOpsExtension@4
            displayName: 'Package extension'
            env:
              TFX_TRACE: '1'
            inputs:
              rootFolder: '$(Pipeline.Workspace)/SourceCode/task'
              publisherId: '$(publisherId)'
              extensionId: '$(extensionId)'
              extensionName: '$(extensionName)'
              extensionVersion: '$(Extension.Version)'
              updateTasksVersion: true
              updateTasksVersionType: 'patch'
              extensionVisibility: '$(visibility)'
              extensionPricing: 'free'
              patternManifest: '**/vss-extension.json'

          - task: PowerShell@2
            displayName: 'Get filename'
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                cd '$(Pipeline.Workspace)';
                $vsixFileFullName = $(Get-ChildItem -Path '.' -Filter '*.vsix' -Recurse).FullName;
                Write-Output "VSIX File Full Name: $vsixFileFullName";
                Write-Host "##vso[task.setvariable variable=vsixFileFullName]$vsixFileFullName";

          - task: PublishPipelineArtifact@1
            displayName: 'Publish VSIX artifact'
            inputs:
              publishLocation: 'pipeline'
              targetPath: '$(vsixFileFullName)'
              artifactName: '$(artifactName)'


          - task: PowerShell@2
            displayName: 'Remove local artifact'
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                Remove-Item -LiteralPath $(vsixFileFullName) -Force -ErrorAction SilentlyContinue;

  - stage: Publish_to_marketplace
    displayName: 'Publish to Marketplace'
    dependsOn: PackageExtension
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: PublishExtension
        displayName: 'Deploy to marketplace'
        environment: 'marketplace-production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: 'Set marketplace service connection auth token'
                  inputs:
                    azureSubscription: 'DevOpsUserAccessAutomation'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    useGlobalConfig: true
                    inlineScript: |
                      $accessToken = az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv
                      Write-Host "##vso[task.setsecret]$accessToken"
                      Write-Host "##vso[task.setendpoint id=$env:MARKETPLACESERVICECONNECTION;field=authParameter;key=password]$accessToken"
                      
                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifactName: '$(artifactName)'
                    targetPath: '$(Pipeline.Workspace)'

                - task: PowerShell@2
                  displayName: 'Get filename'
                  inputs:
                    targetType: 'inline'
                    pwsh: true
                    script: |
                      $vsixFileFullName = (Get-ChildItem -Path '$(Pipeline.Workspace)/$(artifactName)' -Filter '*.vsix' -Recurse).FullName;
                      Write-Output "VSIX File Full Name: $vsixFileFullName";
                      Write-Host "##vso[task.setvariable variable=vsixFileFullName]$vsixFileFullName";

                - task: TfxInstaller@4
                  displayName: 'Install TFX CLI'
                  inputs:
                    version: "v0.x"

                - task: PublishAzureDevOpsExtension@4
                  displayName: 'Publish to marketplace'
                  inputs:
                    connectTo: 'VsTeam'
                    connectedServiceName: '$(marketplaceServiceConnection)'
                    fileType: 'vsix'
                    vsixFile: '$(vsixFileFullName)'
                    publisherId: '$(publisherId)'
                    extensionId: '$(extensionId)'
                    extensionName: '$(extensionName)'
                    updateTasksVersion: false
                    extensionVisibility: '$(visibility)' 
                    extensionPricing: 'free'